<?php include("header.php"); ?>

<main id="main" class="mx-auto" style="max-width:900px">
    <div class="container pb-5">
        <img src="assets/img/st2.jpg" align="left" style="width:30%; margin-right:10px;">
        <p><strong>Pdt. Dr. Stephen Tong</strong> lahir di Xia Men, Provinsi Fu Jian, Tiongkok, pada tahun 1940. Ayahnya meninggal semasa Perang Dunia Il, saat beliau baru berusia 3 tahun. Pada tahun 1949, ibunya membawa beliau dan saudara-saudaranya pindah ke Surabaya, Indonesia.</p>
        <p>Beliau menyelesaikan pendidikan Dasar di SD Min Guang Surabaya, dan lulus SMA di Chung Hwa High School, Surabaya pada tahun 1958. Dari tahun 1957 sampai 1960, beliau mengajar di sekolah Zhong Guo Nui Xue dan di sekolah malam Yi Xing. Ketika berusia 17 tahun, beliau menerima Tuhan Yesus dan menyerahkan diri menjadi hamba Tuhan dalam KKR yang dipimpin oleh Pdt. Dr. Andrew Gih. </p>
        <p>Tahun 1960 beliau belajar theologi di Madrasah Alkitab Asia Tenggara (sekarang SAAT) Malang. Setelah tamat, selama 25 tahun (1964-1988) beliau mengajar theologi dan filsafat di Seminari tersebut. Selain menjabat sebagai dosen SAAT, pada periode tersebut beliau juga melayani di T.H.K.T.K.H/GKT-Fuchow Kuoyu Surabaya (sekarang GKA Gloria) sebagai penginjil tetap setiap akhir minggu, yaitu hari Jumat, Sabtu, dan Minggu, selama 15 tahun (1964-1979). </p>
        <p>Beliau juga menjadi dosen tamu di beberapa universitas, yaitu China Graduate School of Theology di Hong Kong (1975), China Evangelical Seminary di Taiwan (1976), Trinity College di Singapura (1980) dan memberikan ceramah-ceramah di beberapa tempat seperti Westminster Theological Seminary, Philadelphia, USA dan Regent College, Canada</p>
        <p>Pada tahun 1985 beliau menerima gelar kehormatan, yaitu <i>Doctorate in Leadership in Christian Evangelism</i> dari La Madrid International Academy di Manila, kemudian Doctor Of Divinity dari Westminster Theological Seminary, Philadelphia, Amerika Serikat pada tahun 2008 - penghormatan tertinggi yang pernah diberikan oleh Westminster Theological Seminary kepada hamba Tuhan keturunan Tionghoa.</p>
        <p>Sejak tahun 1968, beliau telah menerima undangan memimpin KKR di mancanegara. meliputi Eropa, Amerika, Australia, Jepang, Hong Kong. Taiwan, Thailand. Vietnam, Filipina, Malaysia, Singapura, dll. Pada tahun 1974, beliau muiai mengadakan seminar-seminar di Surabaya untuk memberikan pengertian doktrinal yang benar bagi gereja-gereja di Indonesia.</p>
        <figure style="margin-left:10px; width: 30%; float:right">
            <img src="assets/img/st4.jpg" style="width:100%" alt="Pdt. Dr. Stephen Tong di National University of Singapore">
            <figcaption>Pdt. Dr. Stephen Tong di <i>National University of Singapore</i></figcaption>
        </figure>
        <p>Demi pekabaran Injil, pada tahun 1978, beliau bersama Dr. Jahja Ling mendirikan <a href="https://stemi.org">Stephen Tong Evangelistic Ministries International (STEMI)</a> dengan mengadakan KKR setiap tahun di berbagai kota di dunia. Di samping melayani di berbagai pelosok daerah, beliau juga menjangkau pendengar intelektual di berbagai universitas terkemuka di dunia (Harvard University, Berkeley University, Stanford University, Boston University, Columbia University, Yale University, dll). Beliau pernah menjadi pembicara utama pada kongres-kongres internasional seperti International Prayer Assembly (1985), Leadership Seminar di Amsterdam (1986), Laussane Congress Il (1989), dan berkhotbah di kebaktian penutupan World Reformed Fellowship (April 2006). Beliau juga duduk sebagai anggota Komisi Theologi dari World Reformed Fellowship (WRF) yang merancang Reformed Confession of Faith abad 21.</p>
        <p>Tuhan memberkati pelayanan beliau secara luar biasa. Tahap demi tahap Tuhan membukakan jalan bagi beliau untuk mendirikan <a href="https://pusat.grii.org/">Gereja Reformed Injili Indonesia (GRII)</a> pada tahun 1989. Sebelum mendirikan GRII, beliau aktif mengadakan seminar besar, yaitu Seminar Pembinaan Iman Kristen (SPIK) yang dimulai di Jakarta pada 1984. Kemudian mendirikan Lembaga Reformed Injili Indonesia (LRII) pada 1986. Tahun 1990, beliau mendirikan <a href="https://sttrii.ac.id/">Sekolah Tinggi Theologi Reformed Injili Indonesia (STT-RII)</a>. Pada tahun 1996, beliau mendirikan Reformed Insitute for Christianity, Washington DC, dan pada tahun 1998, mendirikan Institute Reformed di Jakarta. Beliau masih menjabat sebagai rektor dari kedua institusi terakhir ini.</p>
        <p>Sejak tahun 2000 hingga sekarang, setiap minggu Pdt. Dr. Stephen Tong berkeliling ke lima negara (Indonesia, Singapura, Malaysia, Hong Kong, Taiwan) dengan tidak mengenal lelah untuk melayani sekitar 6.000 pendengar. Khotbahnya telah dibukukanPdt. Dr. Stephen Tong dan beberapa hamba Tuhan GRII lainnya, juga menerjemahkan buku Reformed dari bahasa Inggris ke dalam bahasa Indonesia.</p>
        <p>Kerinduan beliau untuk mempermuliakan nama Allah tidak terbatas hanya pada penginjilan saja, tetapi juga dalam mandat budaya. Beliau mendirikan <a href="https://www.instagram.com/jakartaoratoriosociety/">Jakarta Oratorio Society (JOS)</a> pada 1987, untuk memberikan pendidikan mengenai musik-musik yang berkualitas. Pekerjaan dalam mandat budaya juga diteruskan beliau dalam bidang arsitektur dengan merancang beberapa gedung seperti aula SAAT, dan beberapa gedung gereja seperti Gereja Kristus Ketapang, Gepembri, GKI Bungur, dan beberapa gedung lainnya, termasuk karya besarnya (masterpiece), yaitu Reformed Millennium Center Indonesia yang didirikan sejak 2006, dan diresmikan pada 2008.</p>
        <figure style="margin-right:10px; width: 50%; float:left">
            <img src="assets/img/st3.png" alt="Pdt. Dr. Stephen Tong sebagai konduktor di New Years Concert 2023" style="width:100%">
            <figcaption>Pdt. Dr. Stephen Tong sebagai konduktor di <i>New Years Concert 2023</i></figcaption>
        </figure>
        
        <p>Beliau juga mendirikan <a href="https://reformed-crs.org/">Reformed Center for Religion and Society (RCRS)</a> tahun 2006, yang menjalankan mandat budaya menyuarakan peringatan Tuhan untuk menjadi hati nurani masyarakat. Tahun 2009, beliau mendirikan <a href="https://front.aulasimfoniajakarta.com/">Aula Simphonia Orchestra Jakarta (ASJ)</a>, untuk mendidik zaman ini dengan musik yang bermutu. Beliau juga berperan sebagai Music Director, dan pada waktu-waktu tertentu beliau sendiri menjadi konduktor konser. Selanjutnya, untuk pendidikan generasi penerus bangsa yang berilmu dan berkarakter kristiani, beliau mendirikan <a href="https://sekolahkristencalvin.org/">Sekolah Kristen Calvin</a> pada tahun 2008. Sebuah Museum sedang dipersiapkan dan diharapkan bisa diresmikan pada tahun 2011. Museum ini akan menjadi tempat pendidikan kebudayaan yang diisi oleh koleksi barang-barang antik yang sangat bernilai, yang beliau kumpulkan berpuluh-puluh tahun dari seluruh dunia, untuk menjadi sebuah warisan budaya bagi bangsa Indonesia.</p>
        <p>Selama pelayanannya, lebih dari tiga ratus ribu orang telah menyerahkan diri menjadi hamba Tuhan dalam KKR beliau. Hingga kini, lebih dari 2.000 orang hamba Tuhan, baik di dalam maupun di luar negeri, yang pernah dididik di bawah pimpinan beliau. Hingga kini, di usia yang ke-70, Pdt. Dr. Stephen Tong masih berkhotbah dan memimpin puluhan KKR di berbagai penjuru dunia, dan mencapai puluhan ribu pendengar.</p>        
    </div>

  </main><!-- End #main -->
<?php include("footer.php"); ?>
